name: mushroom
channels:
  - conda-forge
  - defaults
dependencies:
  - _libgcc_mutex=0.1=main
  - _openmp_mutex=5.1=1_gnu
  - asttokens=3.0.0=py39h06a4308_0
  - backcall=0.2.0=pyhd3eb1b0_0
  - beautifulsoup4=4.13.4=py39h06a4308_0
  - bleach=6.2.0=py39h06a4308_0
  - brotlicffi=1.0.9.2=py39h6a678d5_1
  - bzip2=1.0.8=h5eee18b_6
  - ca-certificates=2025.2.25=h06a4308_0
  - cffi=1.17.1=py39h1fdaa30_1
  - defusedxml=0.7.1=pyhd3eb1b0_0
  - expat=2.7.1=h6a678d5_0
  - h11=0.16.0=py39h06a4308_0
  - httpcore=1.0.9=py39h06a4308_0
  - httpx=0.28.1=py39h06a4308_0
  - importlib_metadata=8.5.0=hd3eb1b0_0
  - jedi=0.19.2=py39h06a4308_0
  - jinja2=3.1.6=py39h06a4308_0
  - jsonschema=4.25.0=py39h06a4308_0
  - jupyter_client=8.6.3=py39h06a4308_0
  - jupyter_core=5.8.1=py39h06a4308_0
  - jupyter_events=0.12.0=py39h06a4308_0
  - jupyter_server=2.16.0=py39h06a4308_0
  - jupyter_server_terminals=0.5.3=py39h06a4308_0
  - jupyterlab_pygments=0.3.0=py39h06a4308_0
  - jupyterlab_server=2.27.3=py39h06a4308_0
  - ld_impl_linux-64=2.40=h12ee557_0
  - libffi=3.4.4=h6a678d5_1
  - libgcc-ng=11.2.0=h1234567_1
  - libgomp=11.2.0=h1234567_1
  - libsodium=1.0.18=h7b6447c_0
  - libstdcxx-ng=11.2.0=h1234567_1
  - libxcb=1.17.0=h9b100fa_0
  - markupsafe=3.0.2=py39h5eee18b_0
  - nb_conda_kernels=2.5.1=pyh707e725_2
  - nbclient=0.10.2=py39h06a4308_0
  - nbconvert-core=7.16.6=py39h06a4308_0
  - nbformat=5.10.4=py39h06a4308_0
  - ncurses=6.5=h7934f7d_0
  - nest-asyncio=1.6.0=py39h06a4308_0
  - notebook=7.4.4=py39h06a4308_0
  - notebook-shim=0.2.4=py39h06a4308_0
  - openssl=3.0.17=h5eee18b_0
  - packaging=25.0=py39h06a4308_0
  - parso=0.8.4=py39h06a4308_0
  - pexpect=4.9.0=py39h06a4308_0
  - pickleshare=0.7.5=pyhd3eb1b0_1003
  - pip=25.1=pyhc872135_2
  - prometheus_client=0.21.1=py39h06a4308_0
  - pthread-stubs=0.3=h0ce48e5_1
  - ptyprocess=0.7.0=pyhd3eb1b0_2
  - pure_eval=0.2.2=pyhd3eb1b0_0
  - pysocks=1.7.1=py39h06a4308_0
  - python=3.9.23=he99959a_0
  - python-dateutil=2.9.0post0=py39h06a4308_2
  - python-fastjsonschema=2.20.0=py39h06a4308_0
  - pyyaml=6.0.2=py39h5eee18b_0
  - readline=8.2=h5eee18b_0
  - requests=2.32.4=py39h06a4308_0
  - rfc3339-validator=0.1.4=py39h06a4308_0
  - rfc3986-validator=0.1.1=py39h06a4308_0
  - setuptools=78.1.1=py39h06a4308_0
  - six=1.17.0=py39h06a4308_0
  - sqlite=3.50.2=hb25bd0a_1
  - stack_data=0.2.0=pyhd3eb1b0_0
  - tinycss2=1.4.0=py39h06a4308_0
  - tk=8.6.14=h993c535_1
  - tomli=2.2.1=py39h06a4308_0
  - tornado=6.5.1=py39h5eee18b_0
  - traitlets=5.14.3=py39h06a4308_0
  - typing_extensions=4.12.2=py39h06a4308_0
  - urllib3=2.5.0=py39h06a4308_0
  - wcwidth=0.2.13=py39h06a4308_0
  - websocket-client=1.8.0=py39h06a4308_0
  - wheel=0.45.1=py39h06a4308_0
  - xorg-libx11=1.8.12=h9b100fa_1
  - xorg-libxau=1.0.12=h9b100fa_0
  - xorg-libxdmcp=1.1.5=h9b100fa_0
  - xorg-xorgproto=2024.1=h5eee18b_1
  - xz=5.6.4=h5eee18b_1
  - yaml=0.2.5=h7b6447c_0
  - zeromq=4.3.5=h6a678d5_0
  - zlib=1.2.13=h5eee18b_1
  - pip:
      - aiohappyeyeballs==2.6.1
      - aiohttp==3.12.15
      - aiosignal==1.4.0
      - alembic==1.16.4
      - annotated-types==0.7.0
      - antlr4-python3-runtime==4.9.3
      - anyio==4.10.0
      - anywidget==0.9.18
      - argon2-cffi==25.1.0
      - argon2-cffi-bindings==25.1.0
      - arrow==1.3.0
      - async-lru==2.0.5
      - async-timeout==5.0.1
      - attrs==25.3.0
      - autopage==0.5.2
      - babel==2.17.0
      - certifi==2025.8.3
      - cfgv==3.4.0
      - charset-normalizer==3.4.2
      - click==8.1.8
      - cliff==4.9.1
      - cmaes==0.12.0
      - cmd2==2.7.0
      - colorlog==6.9.0
      - comm==0.2.3
      - contourpy==1.3.0
      - cycler==0.12.1
      - debugpy==1.8.15
      - decorator==5.2.1
      - distlib==0.4.0
      - eval-type-backport==0.2.2
      - exceptiongroup==1.3.0
      - executing==2.2.0
      - fastjsonschema==2.21.1
      - filelock==3.18.0
      - fonttools==4.59.1
      - fqdn==1.5.1
      - frozenlist==1.7.0
      - fsspec==2025.7.0
      - gitdb==4.0.12
      - gitpython==3.1.45
      - greenlet==3.2.3
      - hydra-colorlog==1.2.0
      - hydra-core==1.3.2
      - hydra-optuna-sweeper==1.2.0
      - identify==2.6.12
      - idna==3.10
      - importlib-metadata==8.7.0
      - importlib-resources==6.5.2
      - iniconfig==2.1.0
      - ipykernel==6.30.1
      - ipython==8.18.1
      - isoduration==20.11.0
      - json5==0.12.0
      - jsonpointer==3.0.0
      - jsonschema-specifications==2025.4.1
      - jupyter-lsp==2.2.6
      - jupyterlab==4.4.5
      - jupyterlab-widgets==3.0.15
      - kiwisolver==1.4.7
      - lark==1.2.2
      - lightning==2.5.2
      - lightning-utilities==0.15.1
      - mako==1.3.10
      - markdown-it-py==3.0.0
      - matplotlib==3.9.4
      - matplotlib-inline==0.1.7
      - mdurl==0.1.2
      - mistune==3.1.3
      - mpmath==1.3.0
      - multidict==6.6.3
      - narwhals==2.0.1
      - networkx==3.2.1
      - nodeenv==1.9.1
      - numpy==2.0.2
      - nvidia-cublas-cu12==12.6.4.1
      - nvidia-cuda-cupti-cu12==12.6.80
      - nvidia-cuda-nvrtc-cu12==12.6.77
      - nvidia-cuda-runtime-cu12==12.6.77
      - nvidia-cudnn-cu12==9.5.1.17
      - nvidia-cufft-cu12==11.3.0.4
      - nvidia-cufile-cu12==1.11.1.6
      - nvidia-curand-cu12==10.3.7.77
      - nvidia-cusolver-cu12==11.7.1.2
      - nvidia-cusparse-cu12==12.5.4.2
      - nvidia-cusparselt-cu12==0.6.3
      - nvidia-nccl-cu12==2.26.2
      - nvidia-nvjitlink-cu12==12.6.85
      - nvidia-nvtx-cu12==12.6.77
      - omegaconf==2.3.0
      - optuna==2.10.1
      - overrides==7.7.0
      - pandas==2.3.1
      - pandocfilters==1.5.1
      - pbr==6.1.1
      - pillow==11.3.0
      - platformdirs==4.3.8
      - plotly==6.2.0
      - pluggy==1.6.0
      - pre-commit==4.2.0
      - prettytable==3.16.0
      - prometheus-client==0.22.1
      - prompt-toolkit==3.0.51
      - propcache==0.3.2
      - protobuf==6.32.0
      - psutil==7.0.0
      - psygnal==0.14.0
      - pure-eval==0.2.3
      - pycparser==2.22
      - pydantic==2.11.7
      - pydantic-core==2.33.2
      - pygments==2.19.2
      - pyparsing==3.2.3
      - pyperclip==1.9.0
      - pytest==8.4.1
      - python-dotenv==1.1.1
      - python-json-logger==3.3.0
      - pytorch-lightning==2.5.2
      - pytz==2025.2
      - pyzmq==27.0.1
      - rapidfuzz==3.13.0
      - referencing==0.36.2
      - rfc3987-syntax==1.1.0
      - rich==13.7.0
      - rich-argparse==1.7.1
      - rootutils==1.0.7
      - rpds-py==0.26.0
      - scipy==1.13.1
      - send2trash==1.8.3
      - sentry-sdk==2.35.0
      - smmap==5.0.2
      - sniffio==1.3.1
      - soupsieve==2.7
      - sqlalchemy==2.0.42
      - stack-data==0.6.3
      - stevedore==5.4.1
      - sympy==1.14.0
      - taxopy==0.14.0
      - terminado==0.18.1
      - torch==2.7.1
      - torchmetrics==1.8.0
      - torchvision==0.22.1
      - tqdm==4.67.1
      - triton==3.3.1
      - types-python-dateutil==2.9.0.20250708
      - typing-extensions==4.14.1
      - typing-inspection==0.4.1
      - tzdata==2025.2
      - uri-template==1.3.0
      - virtualenv==20.33.0
      - wandb==0.21.1
      - webcolors==24.11.1
      - webencodings==0.5.1
      - widgetsnbextension==4.0.14
      - yarl==1.20.1
      - zipp==3.23.0
prefix: /home/damien/miniconda3/envs/mushroom
